Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -192,7 +192,7 @@ jobs:
         wine winetest64.exe -x winetest64 >/dev/null
         wine winetest64/mscoree_test.exe --list 2>/dev/null|sed 's/.$//'|tail -n +2|while read testname; do
           echo BEGIN $testname TEST 1>&2
-          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree,process,pid WINE_MONO_TRACE=x MONO_LOG_LEVEL=debug gtimeout -v 300 wine winetest64/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 64-bit test failed\n' $testname >> tests-failed
+          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree,process,pid WINE_MONO_TRACE=M:Microsoft.CodeAnalysis.CSharp.CommandLine.Csc:Run MONO_LOG_LEVEL=debug gtimeout -v 300 wine winetest64/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 64-bit test failed\n' $testname >> tests-failed
           echo END $testname TEST 1>&2
         done
         if test -f tests-failed; then
