GitHub CI: Use latest Ubuntu.

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -10,7 +10,7 @@ on:
 jobs:
   build:
 
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
@@ -21,8 +21,12 @@ jobs:
       run: sudo apt remove msodbcsql17 linux-azure linux-cloud-tools-azure linux-headers-azure linux-image-azure linux-tools-azure -y 1>&2
     - name: Install Wine
       run: |
+        sudo dpkg --add-architecture i386 1>&2
+        sudo mkdir -pm755 /etc/apt-keyrings
+        wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
+        . /etc/lsb-release; sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/${DISTRIB_CODENAME}/winehq-${DISTRIB_CODENAME}.sources
         sudo apt-get update 1>&2
-        sudo apt install --install-recommends wine64 wine64-tools -y 1>&2
+        sudo apt install --install-recommends wine-devel-dev wine-devel -y 1>&2
     - name: Install Mono Build Dependencies
       run: |
         sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF 1>&2
@@ -33,13 +37,13 @@ jobs:
       run: |
         gcc --version 1>&2
         g++ --version 1>&2
-        wine --version 1>&2
+        /opt/wine-devel/bin/wine --version 1>&2
         mono --version 1>&2
         ld --version 1>&2
         cmake --version 1>&2
         man libtool | tail -1 1>&2
     - name: make
-      run: make -j$(nproc)
+      run: "PATH=/opt/wine-devel/bin:$PATH make -j$(nproc)"
     - name: msi capture
       uses: actions/upload-artifact@v4
       with:
@@ -97,7 +101,7 @@ jobs:
 
   linux-test:
 
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     needs: build
 
     steps:
@@ -106,49 +110,46 @@ jobs:
     - name: Install Wine
       run: |
         sudo dpkg --add-architecture i386 1>&2
-        wget -nc https://dl.winehq.org/wine-builds/winehq.key 1>&2
-        sudo apt-key add winehq.key 1>&2
-        sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main' 1>&2
+        sudo mkdir -pm755 /etc/apt-keyrings
+        wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
+        . /etc/lsb-release; sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/${DISTRIB_CODENAME}/winehq-${DISTRIB_CODENAME}.sources
         sudo apt update 1>&2
-        sudo apt remove -y libnginx-mod-http-image-filter || true
-        sudo apt remove -y nginx nginx-core || true
-        sudo apt install -y --allow-downgrades libgd3:i386=2.3.0-2ubuntu2 libgd3:i386=2.3.0-2ubuntu2 || true
-        sudo apt install --install-recommends -y --allow-downgrades winehq-devel wine-devel wine-devel-i386 libgphoto2-6:i386 libsane:i386 libgd3:i386 wine-devel-amd64 libgphoto2-6 libsane libgcc-s1:i386 libstdc++6:i386 libatomic1:i386 libegl1:i386 libegl1
+        sudo apt install --install-recommends -y --allow-downgrades winehq-devel wine-devel wine-devel-i386 libgphoto2-6:i386 libsane1:i386 libgd3:i386 wine-devel-amd64 libgphoto2-6 libsane1 libgcc-s1:i386 libstdc++6:i386 libatomic1:i386 libegl1:i386 libegl1
     - name: Download Wine Mono msi
       uses: actions/download-artifact@v4
       with:
         name: make msi output
     - name: Install Wine Mono msi
-      run: wine msiexec /i wine-mono-*.msi 1>&2
+      run: /opt/wine-devel/bin/wine msiexec /i wine-mono-*.msi 1>&2
     - name: Install Wine Gecko
       run: |
         GECKO_VERSION=2.47.4
         wget -nc "https://dl.winehq.org/wine/wine-gecko/${GECKO_VERSION}/wine-gecko-${GECKO_VERSION}-x86.msi" -O wine-gecko-${GECKO_VERSION}-x86.msi
-        wine msiexec /i wine-gecko-${GECKO_VERSION}-x86.msi
+        /opt/wine-devel/bin/wine msiexec /i wine-gecko-${GECKO_VERSION}-x86.msi
         wget -nc "https://dl.winehq.org/wine/wine-gecko/${GECKO_VERSION}/wine-gecko-${GECKO_VERSION}-x86_64.msi" -O wine-gecko-${GECKO_VERSION}-x86_64.msi
-        wine msiexec /i wine-gecko-${GECKO_VERSION}-x86_64.msi
+        /opt/wine-devel/bin/wine msiexec /i wine-gecko-${GECKO_VERSION}-x86_64.msi
     - name: Run 64-bit Wine mscoree tests
       run: |
         wget -nc 'https://gitlab.winehq.org/wine/wine/-/jobs/artifacts/master/raw/winetest64.exe?job=build-daily-winetest' -O winetest64.exe
-        wine winetest64.exe -x winetest64 >/dev/null
-        wine winetest64/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2|while read testname; do
+        /opt/wine-devel/bin/wine winetest64.exe -x winetest64 >/dev/null
+        /opt/wine-devel/bin/wine winetest64/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2|while read testname; do
           echo BEGIN 64-BIT $testname TEST 1>&2
-          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree WINE_MONO_TRACE=x timeout -v 300 wine winetest64/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 64-bit test failed\n' $testname >> tests-failed
+          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree WINE_MONO_TRACE=x timeout -v 300 /opt/wine-devel/bin/wine winetest64/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 64-bit test failed\n' $testname >> tests-failed
           echo END 64-BIT $testname TEST >&2
         done
     - name: Run 32-bit Wine mscoree tests
       run: |
         wget -nc 'https://gitlab.winehq.org/wine/wine/-/jobs/artifacts/master/raw/winetest.exe?job=build-daily-winetest' -O winetest.exe
-        wine winetest.exe -x winetest >/dev/null
-        wine winetest/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2|while read testname; do
+        /opt/wine-devel/bin/wine winetest.exe -x winetest >/dev/null
+        /opt/wine-devel/bin/wine winetest/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2|while read testname; do
           echo BEGIN 32-BIT $testname TEST 1>&2
-          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree WINE_MONO_TRACE=x timeout -v 300 wine winetest/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 32-bit test failed\n' $testname >> tests-failed
+          WINETEST_REPORT_SUCCESS=1 WINEDEBUG=mscoree WINE_MONO_TRACE=x timeout -v 300 /opt/wine-devel/bin/wine winetest/mscoree_test.exe $testname 1>&2 || printf 'mscoree:%s 32-bit test failed\n' $testname >> tests-failed
           echo END 32-BIT $testname TEST 1>&2
         done
     - name: Install Test Dependencies
       run: |
         echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
-        sudo apt install xvfb libgl1-mesa-glx libgl1-mesa-glx:i386 libgl1:i386 libglx-mesa0:i386 libgl1-mesa-dri:i386 unzip ttf-mscorefonts-installer openbox x11-utils -y 1>&2
+        sudo apt install xvfb libgl1 libgl1:i386 unzip ttf-mscorefonts-installer openbox x11-utils -y 1>&2
     - name: Download Wine Mono tests
       uses: actions/download-artifact@v4
       with:
@@ -160,8 +161,8 @@ jobs:
         export DISPLAY=:2
         while ! xdpyinfo; do sleep 1; jobs 1 || exit 1; done
         openbox & 1>&2
-        wine reg add 'HKCU\Software\Wine\WineDbg' /v ShowCrashDialog /t REG_DWORD /d 0 /f 1>&2
-        wine tests/run-tests.exe -fail-list:tests/github-wine-failing.txt 1>&2 || printf 'Wine Mono tests failed\n' >> tests-failed
+        /opt/wine-devel/bin/wine reg add 'HKCU\Software\Wine\WineDbg' /v ShowCrashDialog /t REG_DWORD /d 0 /f 1>&2
+        /opt/wine-devel/bin/wine tests/run-tests.exe -fail-list:tests/github-wine-failing.txt 1>&2 || printf 'Wine Mono tests failed\n' >> tests-failed
     - name: Check for test failures
       run: |
         if test -f tests-failed; then
